baseURL = 'https://blog.pimpa.dog'
languageCode = 'en-us'
title = 'Pimpa the Dog!'
theme = "ananke"
publishDir = "docs"
resourceDir = "./themes/ananke/resources/"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Pimpa"
  favicon = ""
  site_logo = ""
  description = "The best dog"
  background_color_class = "bg-black"
  recent_posts_number = 3
